### ISSUE TITLE
caching function that returns mutable produces confusing behaviour

### ISSUE THREAD

**Issue by cmcaine** [zgornel/Caching.jl#6]
Unclear how to fix this nicely - maybe you want your function to return a reference to the same mutable struct each time and you don't mind that the contents of that struct has changed between function calls?

In my case I've just split my function up so I can cache the immutable string I get from a glorified HTTP.get() operation and I parse the string into a Dict later.

Anyway, I think this should maybe be documented?

**Comment by zgornel** [comment]
Could you provide a minimal example of the issue/bug you are refering to?

**Comment by zgornel** [comment]
Closing for lack of details.
