### ISSUE TITLE
@warn Messages should be @debug instead

### ISSUE THREAD

**Issue by pyramids** [zgornel/Caching.jl#7]
I'm trying to use this interesting package but all the cache-miss (and even cache file creation) warnings annoy me. I like to reserve a warning to something likely to be a user error, so a cache miss IMHO should be a `@debug`, and a cache file creation at most a `@info`.

Could this behavior be changed, perhaps?

**Comment by zgornel** [comment]
Yes, this is a good point, thanks. Will do soon.
